on: [push]
name: Deploy ARM template
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # checkout code
      - uses: actions/checkout@main

      # login to Azure with service principal credentials
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.SP_CREDS }}

      - name: Run ARM template
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          resourceGroupName: ${{ secrets.RG_NAME }}
          template: ./deploy-azure-vm.json
          parameters: ./deploy-azure-vm.parameters.json
          deploymentName: ${{ github.sha }}

      - run: echo ${{ steps.deploy.outputs.SSHLogin }}
